/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import javax.swing.JOptionPane;

import com.mycompany.Services.ServicioPrestamoVehicular;
import com.mycompany.model.PrestamoVehicular;
import com.mycompany.model.TarjetaPropiedad;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIEliminarVehicular extends javax.swing.JFrame {

    /**
     * Creates new form GUIEliminarVehicular
     */
    public GUIEliminarVehicular() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdVehicular = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnBuscarEliminar = new javax.swing.JButton();
        txtMontoPrestamo = new javax.swing.JTextField();
        txtPlazoPrestamo = new javax.swing.JTextField();
        txtValorVehiculo = new javax.swing.JTextField();
        txtMArcaVehiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPlacaVehiculo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Eliminar Prestamo Vehicular");

        jLabel1.setText("ID del Prestamo:");

        jButton1.setText("Eliminar Prestamo Vehicular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarActionPerformed(evt);
            }
        });

        txtMontoPrestamo.setEditable(false);

        txtPlazoPrestamo.setEditable(false);
        txtPlazoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlazoPrestamoActionPerformed(evt);
            }
        });

        txtValorVehiculo.setEditable(false);

        txtMArcaVehiculo.setEditable(false);
        txtMArcaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMArcaVehiculoActionPerformed(evt);
            }
        });

        jLabel2.setText("Monto Prestamo:");

        jLabel3.setText("Plazo del prestamo:");

        jLabel4.setText("Valor comercial Vehiculo:");

        jLabel5.setText("Marca Vehiculo");

        txtPlacaVehiculo.setEditable(false);
        txtPlacaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaVehiculoActionPerformed(evt);
            }
        });

        jLabel6.setText("Placa Vehiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMontoPrestamo)
                            .addComponent(txtPlazoPrestamo)
                            .addComponent(txtValorVehiculo)
                            .addComponent(txtMArcaVehiculo)
                            .addComponent(txtIdVehicular, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtPlacaVehiculo))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarEliminar))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlazoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMArcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // 1. Validar que el campo no esté vacío
        if (txtIdVehicular.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El Campo de ID del Préstamo es obligatorio");
            return;
        }

        try {
            // 2. Eliminar el préstamo por ID
            ServicioPrestamoVehicular prestamoVehicularService = new ServicioPrestamoVehicular();
            boolean eliminado = prestamoVehicularService.eliminar(Integer.parseInt(txtIdVehicular.getText().trim()));

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Préstamo Vehicular eliminado exitosamente");
                // Limpiar los campos de texto después de eliminar
                txtMontoPrestamo.setText("");
                txtPlazoPrestamo.setText("");
                txtValorVehiculo.setText("");
                txtMArcaVehiculo.setText("");
                txtPlacaVehiculo.setText("");
                txtIdVehicular.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el Préstamo Vehicular");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPlacaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaVehiculoActionPerformed

    private void txtMArcaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMArcaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMArcaVehiculoActionPerformed

    private void txtPlazoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlazoPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlazoPrestamoActionPerformed

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        
        // 1. Validar que el campo no esté vacío
        if (txtIdVehicular.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El Campo de ID del Préstamo es obligatorio");
            return;
        }

        try {
            // 2. Buscar el préstamo por ID
            ServicioPrestamoVehicular prestamoVehicularService = new ServicioPrestamoVehicular();
            PrestamoVehicular prestamo = prestamoVehicularService.buscarPorId(Integer.parseInt(txtIdVehicular.getText().trim()));

            if (prestamo != null) {
                // 3. Mostrar los detalles del préstamo en los campos de texto
                TarjetaPropiedad placa = prestamo.getTarjetaPropiedad();
                txtMontoPrestamo.setText(String.valueOf(prestamo.getMonto()));
                txtPlazoPrestamo.setText(String.valueOf(prestamo.getPlazoMeses()));
                txtValorVehiculo.setText(String.valueOf(prestamo.getValorComercial()));
                txtMArcaVehiculo.setText(prestamo.getMarcaVehiculo());
                txtPlacaVehiculo.setText(placa.getPlacaVehiculo());
            } else {
                JOptionPane.showMessageDialog(this, "No se Encontró ese Préstamo Vehicular");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnBuscarEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEliminarVehicular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtIdVehicular;
    private javax.swing.JTextField txtMArcaVehiculo;
    private javax.swing.JTextField txtMontoPrestamo;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtPlazoPrestamo;
    private javax.swing.JTextField txtValorVehiculo;
    // End of variables declaration//GEN-END:variables
}
