/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuCrearHipotecario = new javax.swing.JMenuItem();
        mnuListarHipotecario = new javax.swing.JMenuItem();
        mnuBuscarHipotecario = new javax.swing.JMenuItem();
        mnuEliminarHipotecario = new javax.swing.JMenuItem();
        mnuCuotaMensual = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuCrearVehicular = new javax.swing.JMenuItem();
        mnuListarVehicular = new javax.swing.JMenuItem();
        mnuBuscarVehicular = new javax.swing.JMenuItem();
        mnuEliminarVehicular = new javax.swing.JMenuItem();
        mnuCuotaMensual1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Principal");

        jMenu3.setText("Archivo");

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Prestamo Hipotecario");

        mnuCrearHipotecario.setText("Crear");
        mnuCrearHipotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearHipotecarioActionPerformed(evt);
            }
        });
        jMenu4.add(mnuCrearHipotecario);

        mnuListarHipotecario.setText("Listar");
        mnuListarHipotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarHipotecarioActionPerformed(evt);
            }
        });
        jMenu4.add(mnuListarHipotecario);

        mnuBuscarHipotecario.setText("Buscar");
        mnuBuscarHipotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarHipotecarioActionPerformed(evt);
            }
        });
        jMenu4.add(mnuBuscarHipotecario);

        mnuEliminarHipotecario.setText("Eliminar");
        mnuEliminarHipotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarHipotecarioActionPerformed(evt);
            }
        });
        jMenu4.add(mnuEliminarHipotecario);

        mnuCuotaMensual.setText("Cuota Mensual");
        mnuCuotaMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCuotaMensualActionPerformed(evt);
            }
        });
        jMenu4.add(mnuCuotaMensual);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Prestamo Vehicular");

        mnuCrearVehicular.setText("Crear");
        mnuCrearVehicular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearVehicularActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCrearVehicular);

        mnuListarVehicular.setText("Listar");
        mnuListarVehicular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarVehicularActionPerformed(evt);
            }
        });
        jMenu5.add(mnuListarVehicular);

        mnuBuscarVehicular.setText("Buscar");
        mnuBuscarVehicular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarVehicularActionPerformed(evt);
            }
        });
        jMenu5.add(mnuBuscarVehicular);

        mnuEliminarVehicular.setText("Eliminar");
        mnuEliminarVehicular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarVehicularActionPerformed(evt);
            }
        });
        jMenu5.add(mnuEliminarVehicular);

        mnuCuotaMensual1.setText("Cuota Mensual");
        mnuCuotaMensual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCuotaMensual1ActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCuotaMensual1);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Ayuda");

        jMenuItem3.setText("Acerca de");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrollado por Daniel Ayala \n"
                + "Version 1.0\n"
                + "2026","Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuCrearHipotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearHipotecarioActionPerformed
        GUIAddHipotecario gui = new GUIAddHipotecario();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuCrearHipotecarioActionPerformed

    private void mnuListarHipotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarHipotecarioActionPerformed
        GUIListarHipotecario gui = new GUIListarHipotecario();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuListarHipotecarioActionPerformed

    private void mnuBuscarHipotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarHipotecarioActionPerformed
        GUIBuscarHipotecario gui = new GUIBuscarHipotecario();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuBuscarHipotecarioActionPerformed

    private void mnuEliminarHipotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarHipotecarioActionPerformed
        GUIEliminarHipotecario gui = new GUIEliminarHipotecario();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuEliminarHipotecarioActionPerformed

    private void mnuCrearVehicularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearVehicularActionPerformed
        GUIAddVehicular gui = new GUIAddVehicular();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuCrearVehicularActionPerformed

    private void mnuListarVehicularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarVehicularActionPerformed
        GUIListarVehicular gui = new GUIListarVehicular();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuListarVehicularActionPerformed

    private void mnuBuscarVehicularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarVehicularActionPerformed
        GUIBuscarVehicular gui = new GUIBuscarVehicular();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuBuscarVehicularActionPerformed

    private void mnuEliminarVehicularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarVehicularActionPerformed
        GUIEliminarVehicular gui = new GUIEliminarVehicular();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuEliminarVehicularActionPerformed

    private void mnuCuotaMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCuotaMensualActionPerformed
        GUICuotasMensaulesHipotecario gui = new GUICuotasMensaulesHipotecario();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuCuotaMensualActionPerformed

    private void mnuCuotaMensual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCuotaMensual1ActionPerformed
        GUICuotasMensaulesVehicular gui = new GUICuotasMensaulesVehicular();
        gui.setVisible(true);
    }//GEN-LAST:event_mnuCuotaMensual1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnuBuscarHipotecario;
    private javax.swing.JMenuItem mnuBuscarVehicular;
    private javax.swing.JMenuItem mnuCrearHipotecario;
    private javax.swing.JMenuItem mnuCrearVehicular;
    private javax.swing.JMenuItem mnuCuotaMensual;
    private javax.swing.JMenuItem mnuCuotaMensual1;
    private javax.swing.JMenuItem mnuEliminarHipotecario;
    private javax.swing.JMenuItem mnuEliminarVehicular;
    private javax.swing.JMenuItem mnuListarHipotecario;
    private javax.swing.JMenuItem mnuListarVehicular;
    // End of variables declaration//GEN-END:variables
}
